spring:

  datasource:
    url: ${PGSQL_URL}
    username: ${PGSQL_USER}
    password: ${PGSQL_PASS}

  sql:
    init:
      mode: always
      platform: pgsql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: false
