-- [ROLES]
DROP TABLE roles IF EXISTS;

CREATE TABLE roles (
  id   INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(30) NOT NULL,
  CONSTRAINT pk_roles PRIMARY KEY (id),
  CONSTRAINT uk_roles_name UNIQUE (name)
);

-- [ACCOUNTS]
DROP TABLE accounts IF EXISTS;

CREATE TABLE accounts (
  id       INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  CONSTRAINT pk_accounts PRIMARY KEY (id),
  CONSTRAINT uk_accounts_username UNIQUE (username)
);

-- [ACCOUNTS_ROLES]
DROP TABLE accounts_roles IF EXISTS;

CREATE TABLE accounts_roles (
  account_id INTEGER NOT NULL,
  role_id    INTEGER NOT NULL,
  CONSTRAINT uk_accounts_roles UNIQUE (account_id, role_id),
  CONSTRAINT fk_accounts_roles_account FOREIGN KEY (account_id) REFERENCES accounts (id),
  CONSTRAINT fk_accounts_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

-- [TODOS]
DROP TABLE todos IF EXISTS;

CREATE TABLE todos (
    id        INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(100) NOT NULL,
    completed BOOLEAN NOT NULL,
    priority  VARCHAR(30) NOT NULL,
    author_id INTEGER NOT NULL,
    CONSTRAINT pk_todos PRIMARY KEY (id),
    CONSTRAINT fk_todos_account FOREIGN KEY (author_id) REFERENCES accounts (id)
);